version: '3.8'

networks:
  employee-department:
    name: employee-department

services:

  employee-api:
    image: gurramh/employee-service:v1.0.0
    container_name: employee-api
    ports:
      - 8082:8082
    networks:
      - employee-department

  department-api:
    image: gurramh/department-service:v1.0.0
    container_name: department-api
    ports:
      - 8081:8081
    networks:
      - employee-department