apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service-deployment
spec:
  selector:
    matchLabels:
      app: employee-api
  template:
    metadata:
      labels:
        app: employee-api
    spec:
      containers:
        - name: employee-api
          image: gurramh/employee-service:v1.0.1
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8082
          env:
            - name: DEPARTMENT_URL
              valueFrom:
                configMapKeyRef:
                  name: employee-config
                  key: departmentUrl
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: employee-config
                  key: appName
